### ISSUE TITLE
[Roadmap] Architecture review and refactor

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#1076]
Review 系统的架构设计以及重构，主要目标：

1. 方便测试
2. 方便节点管理

任务列表:

- [x] Refactor Node start, manager and Actor #1079 
- [x] Refactor Chain's create_block_template, MinerService decoupling with ChainService
- [x] Rework on uncles block #1148 
- [x] Rework on Error code #1149
- [ ] Rework on Fast sync

**Comment by jolestar** [comment]
Fast sync tracked by #2000
