### ISSUE TITLE
[TODO] stdlib

### ISSUE THREAD

**Issue by lerencao** [starcoinorg/starcoin#1324]
- [x] 确定 stc 治理功能。
- [x] 确定 stc 代币分发。
- [x] onchain config 更新。
- [x] stdlib review。模块重构，功能增强。gas 优化。spec 增强。

**Comment by lerencao** [comment]
config 更新： #1347 
治理： #1325 
代币 #1343

**Comment by tiangong3624749** [comment]
block prologue txn：[1710](https://github.com/starcoinorg/starcoin/issues/1710)
常用txn的gas费用，例如投票、转账等测试：[1709](https://github.com/starcoinorg/starcoin/issues/1709)
