### ISSUE TITLE
1.0 cleanup and rework

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#1745]
- [x] Cleanup cli command：整理 cli 命令以及参数，ViewObject，统一参数名以及缩写，废弃无用的命令，增加 help. #2001 
- [x] Cleanup log: 是否统一通过 log(target,msg) 的方式记命令？交易执行日志是否应该是 info？如何兼顾 dev 模式下看日志的需求和 production 环境下看日志的需求？#2359
- [ ] Rework on metrics #1738 
- [x] Cleanup dependency #1890 
- [ ] Cleanup storage: 分析是否有冗余的记录
- [x] Cleanup config: 是否需要添加新的配置项？是否要删除冗余的配置项目?  #1634 是否考虑将 config 项和 cli option 统一。
- [x] Cleanup  项目目录结构
- [ ] Node and service start: #1602 #1558

**Comment by jolestar** [comment]
#2026 #2029 rework on config

**Comment by jolestar** [comment]
#2319
