### ISSUE TITLE
1.0 performance optimize

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#1746]
- [x] Sync optimize #1604
- [x] Broadcast optimize #1078 
- [x] Pubsub optimize #1608  
- [x]  Reuse Block and Transaction hash #1761
- [x]  Local benchmark
- [x] Txn gas benchmark #1709 #1710 
- [x] State tree hash cache #1889 
- [ ] Batch state write #1982 
- [ ] Epoch uncle cache #1981

**Comment by jolestar** [comment]
closed for clean
