### ISSUE TITLE
钱包攻击

### ISSUE THREAD

**Issue by fanngyuan** [starcoinorg/starcoin#1957]
- [ ] 盗取 account 的 private_key, password. #1958 
- [ ] 成功盗取节点的 node_key #1959 
- [ ] 校验生成private_key的方法（现在是随机数）是否安全 #1960
