### ISSUE TITLE
[Roadmap]Core Feature

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#272]
- [x] PoW Hash 算法
 - [x] 叔块以及共识机制优化
 - [x] 总量，区块奖励以及减半周期的最终方案
 - [x]  Move stdlib 的稳定
 - [x] 合约的 Event https://github.com/starcoinorg/starcoin/issues/229
 - [x] Rpc 订阅接口  https://github.com/starcoinorg/starcoin/issues/228
 - [ ] ~~状态计费机制~~

**Comment by jolestar** [comment]
1.0 不包含状态计费机制，关闭这个 issue，状态计费通过  #1744 追踪
