### ISSUE TITLE
[Roadmap] Testing

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#274]
- [x]  增加单元测试覆盖率统计 #303 
- [x] Test helper crate and test framework #1073 
- [x]  Cluster test #1074
- [x]  使用 proptest 测试对象序列化 #1075
- [x] fuzzing test #1082 
1. 核心数据结构以及流程覆盖
  - [x] accumulator
  - [x] jellyfish-merkle
  - [x] genesis

2. 公共库测试以及流程覆盖
  - [ ] crypto
  - [ ] decrypt
  - [ ] logger
  - [ ] scmd
  - [ ] stest
  - [ ] sp-utils
  - [ ] metrics
  - [ ] scs

3. 分模块测试覆盖率指标
  - [ ] state
  - [ ] consensus & miner
  - [ ] txpool
  - [ ] chain
  - [ ] sync 
  - [ ] vm  &  executor
  - [ ] network
  - [ ] wallet

4.  性能以及基准测试
 - [x] accumulator
 - [x] jellyfish-merkle
 - [ ] state
 - [ ] txpool
 - [ ] executor
 - [ ] sync
 - [ ] network
 - [ ] rpc
5. 安全测试
 - [ ] consensus
 - [ ] state
 - [ ] rpc
 - [ ] network
 - [ ] vm
6. 兼容性测试
- [ ] Node Compatibility Testing #923 

7. 集成测试
  - [x] cmd & rpc & node
