### ISSUE TITLE
[Roadmap]System upgrade

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#282]
- [x] network versioning support multi protocol 
- [x] on chain config #686 
- [x] multi-signature #276 
- [x] core data structure versioning option
- [x] stdlib upgrade #473

**Comment by fanngyuan** [comment]
- [ ] network versioning
- [ ] chain versioning
- [ ] core data structure versioning
- [ ] on chain config
- [ ] multi-signature

**Comment by jolestar** [comment]
the first stage is finished
