### ISSUE TITLE
[roadmap] storage clean and perf

### ISSUE THREAD

**Issue by nkysg** [starcoinorg/starcoin#2998]
# storage
 - [x] block offline export and import #2997
 - [ ] clean branch block reduce storage size
 - [x] improve execute block with execute block_list 
 - [x] storage write use non-sync
 - [ ] fast sync
 
# performance
- [x] improve MetricsRecord use less system call (now use Instant::now() use clock_gettime)
- [x] cache merkle-tree internal hash
- [x] use improve hash compute

**Comment by templexxx** [comment]
Linux is using vDSO to get time, the cost is about 20-30ns and it won't cause context switch. If you want a pure user-space clock, this lib written me may help: [tsc clock](https://github.com/templexxx/rtsc)

**Comment by nkysg** [comment]
> Linux is using vDSO to get time, the cost is about 20-30ns and it won't cause context switch. If you want a pure user-space clock, this lib written me may help: [tsc clock](https://github.com/templexxx/rtsc). It'll cost only dozens cycles (~ 7ns) to get the timestamp.

thanks,we use clock_gettime
