### ISSUE TITLE
[Roadmap]cli 

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#306]
- [x] Support connect by json rpc #435
- [x] Node and Debug #162 
- [x] Account wallet lock
- [x] ~~Account wallet mnemonic~~ 
- [x] Compile and Deploy contract #186 
- [x] State command enhancement #321
- [x] Console history #345
- [x] AccountAddress display unify #322
- [x] Change default wallet cmd #800
- [x] Query epoch by number #1081 
- [x] Unify cmd command line option style #692
- [x] A rich wallet account implement #878 
- [x] Unify coin balance units #693 
- [x] Support rotate authentication key area #1052 
- [x] Cmd View Object optimize #613 
- [x] command output could be displayed both vertical and horizontal #674
- [x] ~~Support expression in console, Unify integration test and command help~~
