### ISSUE TITLE
[benchmark]Pass benchmark check

### ISSUE THREAD

**Issue by tiangong3624749** [starcoinorg/starcoin#479]
- [x] [accumulator major interface benchmark](https://github.com/starcoinorg/starcoin/issues/340)

- [x] [executor major interface benchmark](https://github.com/starcoinorg/starcoin/issues/342)

- [x] [miner major interface benchmark](https://github.com/starcoinorg/starcoin/issues/343)

- [x] [storage major interface benchmark](https://github.com/starcoinorg/starcoin/issues/344)

- [x] [stateDB and jellyfish-merkle major interface benchmark](https://github.com/starcoinorg/starcoin/issues/341)

- [x] [chain major interface benchmark](https://github.com/starcoinorg/starcoin/issues/339)
