### ISSUE TITLE
[Roadmap]On chain config

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#686]
- [x] Consensus strategy #652 supports change consensus by config.
- [x] ~~Chain network #113  supports detect chain network in Move~~
- [x] Block reward config
- [x] Epoch and Difficulty adjustment
- [x] Feature & SIP flag 
- [x] uncle block config #754 
- [x] Refactor #765 
- [x] OnChainConfig update strategy #788 
- [x] BlockGas limit #997

**Comment by jolestar** [comment]
Move 中不应该关心 ChainNetwork，应该通过初始化参数以及权限解决。关闭 2.

**Comment by jolestar** [comment]
Feature & SIP flag wait  #730
