### ISSUE TITLE
[roadmap] Stabilization first stage

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#921]
## types

- [x] BlockHeader  remove  `consensus_header` field, replace with `nonce`.  should keep gas_limit? #924 
- [x] BlockMetadata and TransactionMetadata need more field ?
- [x] RawUserTransaction 's expiration_time（Duration） replace to expiration_timestamp_secs #879 
- [x] Add a gas_token_code field to  RawUserTransaction，and pass it to VM.  #925
- [x] Add ChainID to transaction #935 
- [x] TransactionOutput's status #938 

## network

- [x] Network message 
- [x] Network rpc api

## stdlib

- [x] Onchain config #686 
- [x] Stdlib error code #791 

## VM

- [x] Upgrade MoveVM for gas fee bug and TransactionOutput's status #926
- [x] Cleanup and stabilization prologue and epilogue arguments.
- [x] Ensure and test stdlib upgrade 

## Testing

- [ ] Node Compatibility Testing #923

**Comment by jolestar** [comment]
BlockMetadata adds uncles and number field.
TransactionMetadata add gas_token_code and chain_id

**Comment by jolestar** [comment]
Network message clean up #1029
